import { Router, Request, Response } from "express"
import { prisma } from "../lib/prisma"

const router = Router()

interface ReportPayload {
  reportId?: string
  orderId?: string
  productName?: string
  formData?: {
    fullName?: string
    birthDate?: string
    birthTime?: string
    birthCity?: string
    birthState?: string
    birthCountry?: string
    timezone?: string | null
    notes?: string | null
  }
}

router.post(["/reports/generate", "/generate-report", "/api/generate-report", "/api/pl-cms/generate-report"], async (req: Request, res: Response) => {
  const authError = validateServiceToken(req)
  if (authError) {
    res.status(authError.status).json({ message: authError.message })
    return
  }

  const payload = normalizePayload(req.body as ReportPayload)
  const formData = payload.formData
  const missing = validatePayload(payload)
  if (missing.length > 0 || !formData) {
    res.status(400).json({ message: `Missing required field${missing.length === 1 ? "" : "s"}: ${missing.join(", ")}` })
    return
  }

  try {
    const reportText = buildReportText(payload, formData)
    const fileName = `${slugify(formData.fullName || "astrology-chart")}-${payload.reportId}.txt`

    await prisma.reportRequest.upsert({
      where: { reportId: payload.reportId! },
      update: {
        orderId: payload.orderId || null,
        productName: payload.productName || null,
        formData,
        reportText,
      },
      create: {
        reportId: payload.reportId!,
        orderId: payload.orderId || null,
        productName: payload.productName || null,
        formData,
        reportText,
      },
    })

    res.json({
      reportId: payload.reportId,
      status: "completed",
      reportText,
      fileName,
    })
  } catch (err) {
    console.error("POST /reports/generate error", err)
    res.status(500).json({ message: "Failed to generate astrology report" })
  }
})

function normalizePayload(payload: ReportPayload): ReportPayload {
  const formData = payload.formData || {}
  const reportId = payload.reportId || `${payload.orderId || "plcms"}-${Date.now()}`

  return {
    ...payload,
    reportId,
    formData: {
      ...formData,
      fullName: cleanString(formData.fullName),
      birthDate: cleanString(formData.birthDate),
      birthTime: cleanString(formData.birthTime),
      birthCity: cleanString(formData.birthCity),
      birthState: cleanString(formData.birthState),
      birthCountry: cleanString(formData.birthCountry),
      timezone: cleanString(formData.timezone),
      notes: cleanString(formData.notes),
    },
  }
}

function validateServiceToken(req: Request): { status: number; message: string } | null {
  const expected = process.env.PL_CMS_API_KEY || process.env.ASTROLOGY_SERVICE_TOKEN
  if (!expected) return null

  const header = req.headers.authorization || ""
  const token = header.startsWith("Bearer ") ? header.slice(7) : ""
  const apiKey = req.headers["x-api-key"]
  const headerKey = Array.isArray(apiKey) ? apiKey[0] : apiKey
  if (token !== expected && headerKey !== expected) {
    return { status: 401, message: "Invalid astrology service token" }
  }
  return null
}

function validatePayload(payload: ReportPayload) {
  const missing: string[] = []
  if (!payload.reportId) missing.push("reportId")
  if (!payload.formData?.fullName) missing.push("formData.fullName")
  if (!payload.formData?.birthDate) missing.push("formData.birthDate")
  if (!payload.formData?.birthTime) missing.push("formData.birthTime")
  if (!payload.formData?.birthCity) missing.push("formData.birthCity")
  if (!payload.formData?.birthState) missing.push("formData.birthState")
  if (!payload.formData?.birthCountry) missing.push("formData.birthCountry")
  return missing
}

function buildReportText(payload: ReportPayload, formData: NonNullable<ReportPayload["formData"]>) {
  const location = [formData.birthCity, formData.birthState, formData.birthCountry].filter(Boolean).join(", ")
  const title = payload.productName || "Astrology Chart"
  const notes = formData.notes?.trim()

  return [
    title,
    "",
    `Name: ${formData.fullName}`,
    `Birth date: ${formData.birthDate}`,
    `Birth time: ${formData.birthTime}`,
    `Birth location: ${location}`,
    formData.timezone ? `Timezone: ${formData.timezone}` : null,
    "",
    "Report status: Generated by api-astrology.",
    "",
    "This report request has been received and saved by the astrology backend. The full chart calculation engine can now be connected here so PL_CMS customers receive the complete generated report automatically.",
    notes ? "" : null,
    notes ? `Customer notes: ${notes}` : null,
  ]
    .filter((line): line is string => line !== null)
    .join("\n")
}

function slugify(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "astrology-chart"
}

function cleanString(value: unknown) {
  return typeof value === "string" ? value.trim() : undefined
}

export default router
